// ProtoIndigo Compiler - Header
#pragma once
#include <vector>
#include <memory>
#include <iostream>
#include <unordered_map>
#include "../parsing/parser.h"
#include "../shared/opcode.h"

namespace wave::internal {
    using runtime_value = std::variant<std::monostate, double, bool, std::shared_ptr<std::string>>;
    using compiler_symbol_table = std::unordered_map<std::string, double>;
    using compiler_output = std::vector<double>;
    using compiler_constant_pool = std::vector<runtime_value>;

    class Compiler {
    private:
        int v_count = 0;                                                            // Variable counts (initialize 0).
        int cp_count = 0;                                                           // Constant Pool counts (initialize 0).
        compiler_symbol_table symbol_table;                                         // Map to translate variable names to number of vm variable position.
        std::vector<std::unique_ptr<Node>> ast;                                     // AST generated by parser.
        compiler_output output;                                                     // Breeze Bytecode generated by Compiler (this).
        compiler_constant_pool constant_pool;                                       // Constant pool generated by Compiler (this).

        void push(OPC opcode);
        void push_const(runtime_value v);
        void store(std::string& identifier);
        void compile_exp(Node& n);
        void compile_binexp(Node& node);
        void compile_node(Node& n);
        void isdefined(std::string identifier);
        
    public:
        Compiler(std::vector<std::unique_ptr<Node>> nodes);
        virtual ~Compiler() = default;
        void compile();
        std::vector<std::unique_ptr<Node>>& getAST() { return ast; };
        std::vector<double>& getOutput() { return output; };
        compiler_constant_pool getCP() { return constant_pool; };
    };
} // namespace wave::internal

// copyright (c) 2026 Victor Botelho Anunciação